{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "severity=\"critical\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "severity=\"warning\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "None",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "severity=\"none\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Operators Degraded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "condition=\"Degraded\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Alerts with State Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "alertname=~\".*Down\"",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "LIst of Alerts",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "labelSelector": "namespace,alertname,condition,reason,message,severity",
     "legendFormat": "{{ summary }}",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}